### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by milezzz** [jojoee/medium-clone#1]
Still working on this?

**Comment by jojoee** [comment]
Hi milezzz,
Yes, I'm still working on it (on my local)
and it'll complete on this Monday (Mon 8 august 2016)

**Comment by milezzz** [comment]
Sweet, I hope I can be first to test it for you =)

**Comment by jojoee** [comment]
Thank you :)
but just let you know, it just layout by this week

**Comment by milezzz** [comment]
Sounds good, I'll be waiting. Probably some of us can help with some of the features you are after.

**Comment by jojoee** [comment]
Hi milezzz,

Apologize me for my under-estimation.
There are many components more than I thought,
anyway I will keep working on it until it's done.

11.33 PM - Mon 8/8/2016

**Comment by milezzz** [comment]
Yeah I hear you...many things to consider.  I have been playing some others but they're on different platforms.

Q:  Were you planning on offering medium style front-end submissions? This might be the biggest challenge. I'd say this is still the best one:  https://github.com/yabwe/medium-editor

**Comment by jojoee** [comment]
Hi milezzz, glad to see you around.

Yes, you are right.
I create this repository cause my passion and challenging myself.
So, normally I working on this repository when I have free time (but I will make it done indeed).

Last, did you have any plan about this repository
(study / using this project / using some part / or something else) ?
If you are here for some reason, so I can invest more time into it :star:
and maybe I  can provide rough estimate for you.

*note - yea, that repo is super GREAT!

**Comment by jojoee** [comment]
Hi @milezzz, how do you do ?
It might be late already.
I just finish version 1.0.3 of this theme in a few days ago, may be you would like to check it out.

FYI
- wordpress.org might take ~5 months before first review
- repository to show theme layout: https://github.com/jojoee/mediumm-template
- review ticket: https://themes.trac.wordpress.org/ticket/41990.
