### ISSUE TITLE
Not Installed

### ISSUE THREAD

**Issue by eksimoron** [jojoee/medium-clone#2]
Please explain more. I can't install.

**Comment by jojoee** [comment]
Hi eksimoron,
It is currently in progress.

**Comment by jestintab** [comment]
when it can be used in real project?

**Comment by jojoee** [comment]
Ok, then I'll start working on it again on tomorrow.
Hopefully, it can be done within this month.

**Comment by jestintab** [comment]
Okay thank you :)

**Comment by jojoee** [comment]
Hey guys

The version 1.0.1 has been published,
and its currently in reviewing on https://themes.trac.wordpress.org/ticket/41990.

Happy songkran day :)

**Comment by jestintab** [comment]
Okay thank you. Greak work!!  I will check it soon :)

**Comment by jojoee** [comment]
FYI,
wordpress.org might take ~5 months before first review
and I've create another repository to show the layout style of this theme here https://github.com/jojoee/mediumm-template
